theme: jekyll-theme-minimal
title: Robyn Ashleigh Dent
description: GAP Graduate Intern 2020
use_logo: true
logo: /assets/images/circularprofile.png

linkedin: robyn-dent-60ab0214a
email: robyn24dent@gmail.com
phone: 011 745 2007 
