theme: jekyll-theme-minimal
title: Robyn Ashleigh Dent
description: GAP Graduate Intern 2020
use_logo: true
logo: /assets/images/circularprofile.png

navbar-links:
  email: robyn24dent@gmail.com
  linkedin: robyn-dent-60ab0214a
  telephone: +27 11 745 2007

